name: ga_user
description: GetArch User feat package,
version: 0.4.1
repository: https://github.com/Hu-Wentao/ga_user

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_arch_core: ^0.4.0
#  get_arch_core:
#    path: D:/flutter_arch/get_arch_core
  get_state: ^3.4.0
  gat_env_info: ^0.4.1

  groovin_material_icons: ^1.1.6
  json_serializable: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.11.2
  injectable_generator: ^0.4.1
  mockito: ^4.1.1

flutter:
